name: txns
channels:
  - conda-forge
dependencies:
  - python
  - compilers
  - numpy=2.1.3
  - pandas=2.2.3
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - networkx=3.4.2
  - scipy=1.14.1
  - lxml=5.3.0
  - pillow=11.0.0
  - pyarrow
  - pymc
  - pip
  - pip:
    - jupyter
    - pymannkendall
    - pycop==0.0.13
    - tqdm
    - XlsxWriter==3.2.0
    - asttokens==2.4.1
    - python_pptx==1.0.2